# Generated by Django 5.2.3 on 2025-06-10 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=10)),
                ('antiguedad', models.CharField(max_length=15)),
                ('especialidad', models.CharField(choices=[('ski', 'Ski'), ('snowboard', 'Snowboard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dni', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('telefono_adulto', models.CharField(max_length=50)),
                ('seguro_vida', models.CharField(max_length=50)),
                ('obra_social', models.CharField(max_length=50)),
                ('alergias', models.TextField(blank=True)),
                ('intervenciones_medicas', models.TextField(blank=True)),
                ('motricidad_reducida', models.TextField(blank=True)),
                ('usa_lentes', models.BooleanField(default=False)),
                ('info_extra', models.TextField(blank=True)),
                ('nivel_ski', models.CharField(max_length=50)),
                ('historial_clases', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('MD', 'Medio día'), ('DC', 'Día completo')], max_length=2)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.alumno')),
            ],
        ),
    ]
