# Generated by Django 5.2 on 2025-05-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=10)),
                ('antiguedad', models.CharField(max_length=15)),
                ('especialidad', models.CharField(choices=[('ski', 'Ski'), ('snowboard', 'Snowboard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('MD', 'Medio día'), ('DC', 'Día completo')], max_length=2)),
                ('dias', models.CharField(max_length=100)),
            ],
        ),
    ]
