# Generated by Django 5.2 on 2025-05-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_turno_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.instructor'),
            preserve_default=False,
        ),
    ]
