# Generated by Django 5.2.1 on 2025-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_turno_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dias',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
